language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install vuepress
  - npm run build

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  local_dir: docs
  # target_branch: master 
  # default to gh-pages
  on:
    branch: master